packages:
  - apps/*
  - packages/*

allowBuilds:
  "@bufbuild/buf": true
  esbuild: true
autoInstallPeers: false
engineStrict: true
preferWorkspacePackages: true
saveExact: true
strictDepBuilds: true
strictPeerDependencies: true
